import Head from "next/head";
import Image from "next/image";
import Github from "../section/Github";
import Twitter from "../section/Twitter";
import Youtube from "../section/Youtube";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Adamu <br /> Abubakar's <br /> Social Stats
        </h1>
        <div className={styles.smDashboard}>
          <Github />
          <Twitter />
          <Youtube />
        </div>
      </main>
    </div>
  );
}
